# fly.toml app configuration file generated for cf-tdm-withered-glade-2785 on 2024-05-09T04:56:54+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cf-tdm-withered-glade-2785'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
